### PR TITLE
Make exechooks work like webhooks.

### PR DESCRIPTION
**Pull request by thockin**
This is a port of #437 by @eminugurkenar.
    
This deprecates the `--sync-hook-command` flag in favor of `--exechook-command`, `--exechook-timeout`, and `--exechook-backoff`.

This also highlighted some issues which may need to port back to v3 branch.

### CODE REVIEW

**Comment by eminugurkenar** [comment]
@thockin , i just noticed something i named environent vars wrongly i guess.

I think you would like to change them like below ? to make them consistent with webhook env vars.

GIT_EXECHOOK_COMMAND -> GIT_SYNC_EXECHOOK_COMMAND
GIT_EXECHOOK_TIMEOUT    -> GIT_SYNC_EXECHOOK_TIMEOUT
GIT_EXECHOOK_BACKOFF    -> GIT_SYNC_EXECHOOK_BACKOFF

**Comment by thockin** [comment]
Oops!  I'll fold those in.  Good catch

**Comment by eminugurkenar** [comment]
README.md needs to be updated as well , sorry for that:<

**Comment by thockin** [comment]
No sweat.  We both missed it :)

**Review by stp-ip — APPROVED** [review]
/lgtm

**Pull request merged**
