### PR TITLE
Fix bug when using GIT_SYNC_REV, and GIT_SYNC_ONE_TIME

### PR DESCRIPTION
**Pull request by yoyehan**
- When using git-sync to sync specific commits, git-sync fails after syncing the first time.
- Error occurs when different commit hashes (not tags) are inputed to GIT_SYNC_REV, and GIT_SYNC_ONE_TIME = true is used.
- Using a commit hash in rev config fails since GetRevs function doesn't account for the possibility that git.rev can be a commit hash. 
- I added a simple function to check if the given rev is a hash (and not a tag) that exists in the remote repository, and returns a HEAD hash for local, and a full given commit for remote to ensure that sync does happen.

### CODE REVIEW

**Comment by thockin** [comment]
Can you show me a test-case (or several) that highlight the problems?  test_e2e.sh is where to look.

> When using git-sync to sync specific commits, git-sync fails after syncing the first time.

I don't see that at HEAD (which I know is not released):

```
{"logger":"","ts":"2022-12-22 19:03:13.217301","caller":{"file":"main.go","line":481},"level":0,"msg":"starting up","pid":12,"uid":8119,"gid":89939,"home":"/tmp","args
":["/git-sync","-v=6","--add-user","--touch-file=_sync_lock","--period=100ms","--repo=file:///tmp/git-sync-e2e.27408267/repo","--branch=e2e-branch","--rev=eccdcb1c9691
b891b9cf595ece3054bfd70550e8","--root=/tmp/git-sync-e2e.27408267/root","--link=link"],"env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","HOSTN
AME=thockin-glaptop4","ENVKEY=envval","HOME=/tmp","GIT_SYNC_ROOT=/tmp/git"]}
...
{"logger":"","ts":"2022-12-22 19:03:13.341786","caller":{"file":"main.go","line":752},"level":0,"msg":"rev appears to be a git hash, no further sync needed","rev":"eccdcb1c9691b891b9cf595ece3054bfd70550e8"}
```

and 

```
{"logger":"","ts":"2022-12-22 19:03:17.832515","caller":{"file":"main.go","line":481},"level":0,"msg":"starting up","pid":11,"uid":8119,"gid":89939,"home":"/tmp","args":["/git-sync","-v=6","--add-user","--touch-file=_sync_lock","--one-time","--repo=file:///tmp/git-sync-e2e.27408267/repo","--branch=e2e-branch","--rev=b2ac4dcda1dbcff8d9aff00d40eaca4449d44279","--root=/tmp/git-sync-e2e.27408267/root","--link=link"],"env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","HOSTNAME=thockin-glaptop4","ENVKEY=envval","HOME=/tmp","GIT_SYNC_ROOT=/tmp/git"]}
...
{"logger":"","ts":"2022-12-22 19:03:17.951862","caller":{"file":"main.go","line":744},"level":2,"msg":"exiting after one sync","status":0}
```

> Error occurs when different commit hashes (not tags) are inputed to GIT_SYNC_REV, and GIT_SYNC_ONE_TIME = true is used.

I don't quite follow this.  An e2e example would help.

**Comment by yoyehan** [comment]
The test case doesn't exist in e2e script.
On an empty directory, if I run the following two git sync jobs consecutively, the second job fails.
```
1. --repo=https://github.com/kubernetes/git-sync --root=/tmp/git-sync --one-time=true --rev=482bf07d574a3170a78b2a4a4a3164339dd3c259
2. --repo=https://github.com/kubernetes/git-sync --root=/tmp/git-sync --one-time=true --rev=a761413d81677d295e6fa53134bcf150e6bf5707
```
The second job fails with the following error message:

> "msg":"can't resolve commit, will retry","error":"Run(git cat-file -t ): exit status 128: { stdout: \"\", stderr: \"fatal: Not a valid object name\" }","rev":"a761413d81677d295e6fa53134bcf150e6bf5707","hash":""}

This seems to occur because **GetRevs** function doesn't account for a case when a user inputs a commit hash for --rev config.

Apologies for not adding a test case to e2e-test script. Getting a no match for platform in manifest error when building test image.

**Comment by thockin** [comment]
I see - it's about back-to-back runs with different revs.

Can you show me what error you get on e2e?  If you wrote an e2e case it would help me a lot.

**Comment by yoyehan** [comment]
@thockin Added "sync_sha_multiple_times" test case and included in the PR.

**Comment by thockin** [comment]
I think I have a different approach which builds off your e2e case - will post more once it works :)

**Comment by thockin** [comment]
See #656 - it passes all tests.  Thanks for clarifying a good use case that was under-tested.

**Pull request closed without merging**
