### PR TITLE
Add a test to exercise git

### PR DESCRIPTION
**Pull request by thockin**
I keep having to cross-check whether things work the way I think they work.  I am codifying them into a test.

### CODE REVIEW

**Comment by stp-ip** [comment]
Am I missing something or is this mostly for running it manually within a manually spun up container?
Any reason to not run this alongside the e2e tests?

**Comment by thockin** [comment]
I was trying to make it simple - something I could quickly run to confirm
behavior rather than manual tests.  I left a TODO to containerize it, but
it is mostly aimed at me while I'm doing a large PR for V4.

**Comment by stp-ip** [comment]
Yeah saw the TODO, just wanted to check in, that I didn't miss anything.

/lgtm

**Comment by thockin** [comment]
I'm working on a big one and I am trying to make it as contained as possible by peeling off anything I can :)

**Pull request merged**
