### PR TITLE
Add --git-config flag

### PR DESCRIPTION
**Pull request by thockin**
This allows arbitrary git configs to be passed in.  For example:

`git config --global http.postBuffer 1048576000`

`git config --global http.sslCAInfo /path/to/cert/file`

`git config --global http.sslVerify false`

This flag takes a comma-separated list of `key:val` pairs.  The key part
is passed to `git config` and must be a valid gitconfig section header
and variable name.  The val part can be either a quoted or unquoted
value.  For all values the following escape sequences are supported:
   * `\n` => [newline]
   * `\t` => [tab]
   * `\"` => `"`
   * `\,` => `,`
   * `\\` => `\`

Within unquoted values, commas MUST be escaped. Within quoted values,
commas MAY be escaped, but are not required to be.  Any other escape
sequence is an error.

Example:

`--git-config=foo.one:val1,foo.two:"quoted val",foo.three:12345`

This commit exposed a bug in runCommand() which modified its args when
they had an embedded space.

Replaces #240 (thanks to @onesolpark for starting it)

### CODE REVIEW

**Comment by stp-ip** [comment]
Ran into an issue. Investigating.

**Comment by thockin** [comment]
I think tests on master (v4) are unhappy.  I can tackle that independently.

/hold

**Comment by stp-ip** [comment]
Yeah. I missed that in the review #351 as far as I can see. It's due to the file/dir being ambigious to the revision as we removed the "rev-".
Will check it out and overall shouldn't be a blocker here once I boiled down the issue I guess.

**Comment by thockin** [comment]
I have a trivial fix - coming momentarily.

**Comment by thockin** [comment]
https://github.com/kubernetes/git-sync/pull/353

**Pull request merged**
