### PR TITLE
fix(auth): Fix ssh authentication

### PR DESCRIPTION
**Pull request by yyvess**
## Ssh authentification 
Fix ssh authentification break by https://github.com/kubernetes/git-sync/commit/d5c61f7ad19dea6ae6938dcb5dea7daa0b54676b

User must not be extracted from ssh as ssh://git@github.com/kubernetes/git-sync.git

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
OMG!  Thanks.  I'll craft an e2e test.  How embarrassing.

**Comment by thockin** [comment]
Oof, I need a CLA signed in order to merge this.  Otherwise I can recreate it along with the e2e test (if you can't sign CLA).

/approve
/lgtm

**Comment by yyvess** [comment]
@thockin sign CLA

**Pull request merged**
