### PR TITLE
Add libnss_wrapper and a wrapper to use it

### PR DESCRIPTION
**Pull request by Vampouille**
Compile libnss_wrapper from source and create a script that populate at
runtime passwd/group databases with current running user.

### CODE REVIEW

**Comment by Vampouille** [comment]
I'm not very confortable with building libnss_wrapper in this image as said by @tianon here : https://github.com/docker-library/postgres/pull/543 it is the responsibility of this repository to maintain build instructions of libnss_wrapper ?

**Comment by thockin** [comment]
If we switch to debian as a base, this gets easier right?  #154

**Comment by thockin** [comment]
Closing as abandoned for now.

**Pull request closed without merging**
