### PR TITLE
Add GC controls, e2e regexes (v3 branch)

### PR DESCRIPTION
**Pull request by thockin**
Looking for feedback, re: #439.  This does not solve the timeout problem, and it does not do ideal repo-packing, but that is bigger and will have to come in v4 only.

Set `gc.autoDetach` to "false"

Add `--git-gc` flag to control GC on each sync
Values:
* "auto" - run `git gc --auto` (default, respects git gc.* configs)
* "always" - run `git gc`
* "aggressive" - run `git gc --aggressive` (may require a longer timeout)
* "off" - do not run `git gc` on each sync (good for --one-time use)

Also makes e2e test treat args as regexes.

### CODE REVIEW

**Comment by thockin** [comment]
OK, I think this is ready for review.

**Comment by thockin** [comment]
ping on this if anyone cares

**Review by stp-ip — APPROVED** [review]
/lgtm

**Comment by stp-ip** [comment]
Might wanna update the Readme with the latest gc arg.

**Pull request merged**
