### PR TITLE
Update ssh.md

### PR DESCRIPTION
**Pull request by sjernigan**
Adding requirement for runAsRoot and suggested configuration for defaultMode.  These are required after previous change to remove the chmod on the key.

See disccussion #33 and #34 #

### CODE REVIEW

**Comment by stp-ip** [comment]
Afaik the runAsRoot shouldn't be necessary, when the credentials are modified via defaultMode. During my investigation it seemed as defaultMode has no effect in any of my clusters.
Will investigate further and see, if this PR makes sense to merge as is.

If you want to pinpoint the details, could you check, if defaultMode does in fact change the permissions on your clusters?

**Comment by sjernigan** [comment]
I signed the CLA

**Comment by sjernigan** [comment]
With the changes suggested (runAsRoot and defaultMode), it works.  If I remove the defaultMode only, I get 
"ERROR: can't configure SSH: Permissions -rw-r--r-- for SSH key are too open. It is recommeded to mount secret volume with `defaultMode: 256` (decimal number for octal 0400)."

**Comment by sjernigan** [comment]
Perhaps it should also be noted in the docs that it will fail to pull a public repo via SSH if the SSH key config isn't correct.  However, you can use the https form in GIT_SYNC_REPO

**Comment by sjernigan** [comment]
Finally, the defaultMode change by itself also doesn't work.  The SSH key is owned by root despite the container user being set to nobody in the dockerfile.  Seems like there should be a user option in volumeMount but I didn't find one.

**Comment by stp-ip** [comment]
Thanks for checking it out. Yeah I assumed that the permission change is somehow affected by the container running as nobody. Will merge this for now and open an issue to try fixing it. I don't like running containers as root.

**Pull request merged**
