### PR TITLE
Update RELEASING doc

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Review by nan-yu — APPROVED** [review]
Thanks for updating the release note.

**Comment by nan-yu** [comment]
@thockin Can you grant me access to the `k8s-staging-git-sync` project? I'm having permission issue when trying to push an image.

```
denied: Token exchange failed for project 'k8s-staging-git-sync'. Caller does not have permission 'storage.buckets.get'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control
```

**Comment by thockin** [comment]
Regarding permissions: https://github.com/kubernetes/k8s.io/pull/2264 was still held - my fault.  Should merge and reconcile soon.

What are you pushing up there?  Just trying it out or doing something with it?

**Comment by nan-yu** [comment]
I was just trying out the release process.

**Pull request merged**
