### PR TITLE
add usage docs

### PR DESCRIPTION
**Pull request by arturozv**
Hi, thanks for the project! 
I've been having to check the source code to check what options does the cli have. It would be nice to have them on a more friendly format

### CODE REVIEW

**Comment by arturozv** [comment]
CLA done

**Comment by stp-ip** [comment]
The CLA is still having a problem as the username on the commit is different than the one from the commit.

**Comment by thockin** [comment]
How do we ensure this is kept up to date?

Would you consider adding a step to the tests to regenerate it and diff, and fail if the diff is not empty?

We should set up Travis for this, too, but that's not your problem.

**Comment by stp-ip** [comment]
Automating that would be great, but we could start by asking for an update on PRs adding new features.

**Comment by thockin** [comment]
I promise this will go stale.  Did you run a script to generate this?

**Comment by arturozv** [comment]
@thockin I did not use a script, if I remember well I took the output from the help command, fix some default values that were set up for my specific configuration and compare to the code to add some missing ones not specific to git-sync like the loglevel

**Pull request closed without merging**
