### PR TITLE
docs: add PAT option for `--password`

### PR DESCRIPTION
**Pull request by andres-lowrie**
This could help users that are not aware that github personal access tokens can be used as passwords. It's verbose could be helpful

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
I'm going to need you to sign the CLA or the bots won't merge it.

Thanks!

**Comment by andres-lowrie** [comment]
CLA signed

**Comment by stp-ip** [comment]
Thanks 
/check-cla

**Comment by andres-lowrie** [comment]
> Thanks
> /check-cla

spoke too soon, I registered with the foundation but haven' received the actual email my bad... I'll reply when that arrives in my inbox

**Comment by andres-lowrie** [comment]
apparently I'm extra stupid and forgot to request a form after I signed up for linux foundation rofl... good times. I signed it

**Pull request merged**
