### PR TITLE
Multiarch via buildx

### LINKED ISSUE #222: Multi arch build?
Can we get multi arch builds by any chance? I needed to build my own image for a Raspberry Pi. Kubernetes on arm is getting more popular.

### PR DESCRIPTION
**Pull request by thockin**
We'll probably want to cut a 3.1.7 for this.  Test build is up at thockin/git-sync:v3.1.6-dirty__linux_arm64 and manifest at  thockin/git-sync:v3.1.6-dirty.

Fixes #222

### CODE REVIEW

**Comment by stp-ip** [comment]
Will see that I can test it on a raspberry at the latest Monday.

**Comment by thockin** [comment]
Great!

**Comment by stp-ip** [comment]
/approve
Code, build and running it on armv7 all good. LGTM

Documenting this here as during testing in a clean environment as well it showed up:
The new docker build process (such as `make all-container`) now needs the experimental flag set for the docker daemon as buildx is still experimental. To be thorough it also needs qemu (qemu-user) as an additional dep.

**Comment by thockin** [comment]
I am building 3.1.7

**Comment by thockin** [comment]
https://github.com/kubernetes/git-sync/releases/tag/v3.1.7

**Comment by flavio** [comment]
@thockin thanks for taking care of that. Everything works as expected also on ARM64

**Comment by thockin** [comment]
Thanks for confirming

**Pull request merged**
