### PR TITLE
Change libcurl workaround to be less precise (v3)

### PR DESCRIPTION
**Pull request by thockin**
This should work across platforms more cleanly.

### CODE REVIEW

**Comment by thockin** [comment]
self-merge to cut a release

**Comment by stp-ip** [comment]
Not sure I get the reasoning here. Wasn't the point downgrading libcurl?

**Comment by thockin** [comment]
The way it was set up before, we install the backports git, which
dragged the backported libcurl.  Then we downgraded it to stable.

The way it is now, we install the stable git, which drags in stable
libcurl, then upgrade ONLY git.  Same net result, but we don't have to
specify a particular version or architecture.

**Comment by stp-ip** [comment]
Thanks for clarifying

**Pull request merged**
