### PR TITLE
support --depth flag for submodules

### PR DESCRIPTION
**Pull request by michallula**
Follow up of https://github.com/kubernetes/git-sync/pull/185 with --depth flag support.

### CODE REVIEW

**Comment by michallula** [comment]
@thockin PR with depth support as I promised before. As I said, tests fails (at least on Mac, git version 2.23.0) cause `--depth` flag doesn't prevent from fetching whole history of submodule repository. Any ideas what is wrong here?

**Comment by thockin** [comment]
git.2.23.0 on Linux also seems to fail

```
testcase submodule-sync-depth: FAIL:  forward submodule depth mismatch expected=1 actual=2
```

**Comment by thockin** [comment]
Running manually I see:

```
$ git submodule update --init --recursive --depth 1
Cloning into '/tmp/git-sync-test.3215/root/rev-719f2db72cbd4446681db56818fc2e26a6d3003b/sub'...
warning: --depth is ignored in local clones; use file:// instead.
```

Changing the `submodule add` line to "file://$SUBMODULE" makes the test pass.

Can you integrate that (and in the other submodule test) and confirm.  Ping me when ready for another look.

Thanks!

**Comment by michallula** [comment]
@thockin nice catch, haven't noticed it before. Thanks a lot for debugging. I've updated tests and they pass indeed. Please make review once again.

**Pull request merged**
