### PR TITLE
add socat to image to allow for proxying. Fixes #279

### LINKED ISSUE #279: Include socat or nc in image
Related to https://github.com/kubernetes/git-sync/issues/180 - could nc or socat (preferrably socat) be included in the image to allow for proxying?

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David Karlsen <david@davidkarlsen.com>

### CODE REVIEW

**Comment by stp-ip** [comment]
Don't personally run in a proxy environment, but can see the reasoning. It's a small dep, that should be ok to add.

/approve
Waiting for a merge from @thockin, if he agrees.

**Comment by thockin** [comment]
Can you document somewhere exactly how one would use this?  Maybe a short new markdown under docs/ ?

**Comment by davidkarlsen** [comment]
@thockin added docs

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by davidkarlsen** [comment]
@thockin thanks for merging, will you do a release in near future?

**Comment by thockin** [comment]
Workin on a 3.1.7 build

**Comment by thockin** [comment]
https://github.com/kubernetes/git-sync/releases/tag/v3.1.7

**Comment by davidkarlsen** [comment]
Thanks - works perfectly https://github.com/evryfs/helm-charts/releases/tag/opsgenie-marid-0.2.0

**Comment by thockin** [comment]
Thanks for the confirmation

**Pull request merged**
