### PR TITLE
e2e: Allow N tests to fail and catch errexit

### LINKED ISSUE #611: e2e: `errexit` does not work in a function if called in `if`
All of the e2e functions are called under `if` and bash says that ignores errexit.  Need to find a way to convert that to `return 1` or something

### PR DESCRIPTION
**Pull request by thockin**
Prior to this, `errexit` was not active inside test functions (see
comments in this commit).

Now, multiple tests can fail - it does not abort on the first one.

Fixes #611

### CODE REVIEW

**Comment by stp-ip** [comment]
Got a few tests not passing with this. Haven't been able to pinpoint and worked through the other PRs for now.

**Comment by thockin** [comment]
Interesting.  I'll re-run locally.  It passed for me before.  I have another few diffs which will make it a bit more deterministic

**Comment by thockin** [comment]
I found a few issues that this exposed - runs that we expect to fail were causing failures, and some non-compliant fake-HTTP responses.

PTAL

**Review by stp-ip — APPROVED** [review]
/lgtm

**Pull request merged**
